const toastRegion = document.querySelector('[data-toast-region]');
let toastTimer;
function showToast(message) { toastRegion.textContent = message; toastRegion.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toastRegion.classList.remove('is-visible'), 2400); }
const interactiveSelector = 'button, a:not(.skip-link)';
document.addEventListener('pointerdown', (event) => { const control = event.target.closest(interactiveSelector); if (!control || event.button > 0) return; const bounds = control.getBoundingClientRect(); const ripple = document.createElement('span'); ripple.className = 'ripple'; ripple.setAttribute('aria-hidden', 'true'); ripple.style.left = `${event.clientX - bounds.left}px`; ripple.style.top = `${event.clientY - bounds.top}px`; control.append(ripple); ripple.addEventListener('animationend', () => ripple.remove(), { once: true }); });
document.querySelectorAll('[data-toast]').forEach((element) => element.addEventListener('click', () => showToast(element.dataset.toast)));
const form = document.querySelector('[data-editor-form]');
const saveState = document.querySelector('[data-save-state]');
let saveTimer;
form.addEventListener('input', (event) => { if (event.target.name === 'title') updatePreviewTitle(event.target.value); if (event.target.name === 'date') updatePreviewDate(event.target.value); saveState.classList.add('is-saving'); saveState.classList.remove('is-error'); saveState.innerHTML = '<i></i> Saving draft...'; clearTimeout(saveTimer); saveTimer = setTimeout(() => { saveState.classList.remove('is-saving'); saveState.innerHTML = '<i></i> Saved as draft'; }, 700); });
function updatePreviewTitle(value) { const title = value.trim() || 'Untitled event'; document.querySelector('[data-preview-title]').innerHTML = title.toUpperCase().replace(/\s+/g, '<br>'); }
function updatePreviewDate(value) { if (!value) return; const date = new Date(`${value}T00:00:00`); document.querySelector('[data-preview-date]').textContent = date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase(); }
document.querySelector('[data-add-ticket]')?.addEventListener('click', () => { const list = document.querySelector('.ticket-type-list'); const row = document.createElement('div'); row.className = 'editor-ticket-row'; row.innerHTML = '<div><strong>New tier</strong><span>Describe this access</span></div><input type="number" value="200000" aria-label="New tier price"><input type="number" value="100" aria-label="New tier quantity"><button type="button" data-toast="Ticket type removed" aria-label="Remove new ticket type">×</button>'; list.append(row); showToast('New ticket type added'); });
document.querySelector('[data-upload]')?.addEventListener('click', () => showToast('Image picker preview opened'));
document.querySelector('[data-preview]')?.addEventListener('click', () => showToast('Event preview opened'));
document.querySelector('[data-publish]')?.addEventListener('click', (event) => { const publishButton = event.currentTarget; if (!document.querySelector('[data-confirm]').checked) { document.querySelector('[data-publish-warning]').hidden = false; document.querySelector('[data-editor-status]').textContent = 'Confirm the details before publishing.'; return; } document.querySelector('[data-publish-warning]').hidden = true; publishButton.classList.add('is-pending'); publishButton.innerHTML = '<span>Publishing...</span><span aria-hidden="true">...</span>'; setTimeout(() => { publishButton.classList.remove('is-pending'); publishButton.innerHTML = '<span>Published</span><span aria-hidden="true">✓</span>'; document.querySelector('[data-editor-status]').textContent = 'Event published successfully.'; showToast('Event published'); }, 800); });
